databases:
  - name: learning_log
    databaseName: 
    user: 

services:
  - type: web
    name: learning_log
    env: python3.10.6
    buildCommand: "./build.sh"
    startCommand: "gunicorn learning_log.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: learning_log
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4